########################################################### 
# Makefile for CS570 Assignment #3
# Ryan Ragasa (cssc1144)
# Paul Nguyen (cssc1143)
###########################################################

FILE=a3.c
CC=gcc
ENDFLAGS=-lpthread
FLAGS=-lrt
NAMEFILE=bots

run:
	$(CC) $(FILE) -o $(NAMEFILE) $(FLAGS) $(ENDFLAGS)

clean:
	rm -f *.o
	rm -f $(NAMEFILE)

#######################[ EOF: Makefile ]###################
