# Paul Nguyen cssc1143
# Ryan Ragasa cssc1144
# Assignment #2 Algorithms Analysis
# Makefile file
# 6/19.2017 CS570 Summer 2017
# function: Makefile
############################################################

CC = gcc
FILE = a2.c 
OUT_EXE = bots

run: 
	$(CC) $(FILE) -o $(OUT_EXE) $(FILES)

clean:
	rm -f *.o
	rm -f $(OUT_EXE)


#######################[ EOF: Makefile ]####################
